global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 5s
rule_files:
  - /etc/prometheus/rules.yml
scrape_configs:
- job_name: primary
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - exporter:9187
    labels:
      server: "primary"
- job_name: replica
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - replica:9187
    labels:
      server: "replica"
