{
 "title": "PostgreSQL Observability",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "node", "label": "Noeud", "query": { "query": "label_values(pg_static, job)" } }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum by(exported_server, instance, job, server) (pg_stat_database_numbackends) / pg_settings_max_connections",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 1 },
   "targets": [
    { "expr": "pg_static" }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  },
  {
   "title": "Native Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 8 },
     "repeat": "node",
     "options": {
      "content": "<center> <h1 style=\"text-transform: capitalize;\">${node} </h1></center>"
     }
    },
    {
     "title": "Connexions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "repeat": "node",
     "targets": [
      {
       "expr": "pg_stat_activity_count{job=\"$node\"}",
       "legendFormat": "{{datname}} {{state}}"
      }
     ]
    },
    {
     "title": "Verrou",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "repeat": "node",
     "targets": [
      {
       "expr": "pg_locks_count{job=\"$node\"}",
       "legendFormat": "{{mode}} sur {{datname}}"
      }
     ]
    },
    {
     "title": "Tuples activity",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "repeat": "node",
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_deleted{job=\"$node\"}[$__rate_interval])",
       "legendFormat": "Tuples deleted on {{datname}} "
      },
      {
       "expr": "rate(pg_stat_database_tup_inserted{job=\"$node\"}[$__rate_interval])",
       "legendFormat": "Tuples inserted on {{datname}}"
      },
      {
       "expr": "rate(pg_stat_database_tup_updated{job=\"$node\"}[$__rate_interval])",
       "legendFormat": "Tuples updated on {{datname}}"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "repeat": "node",
     "targets": [
      {
       "expr": "rate(pg_stat_database_xact_commit{job=\"$node\",datname!=\"\"}[$__rate_interval])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "max_connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "pg_settings_max_connections", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "shared_buffers",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_shared_buffers_bytes",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "work_mem",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "pg_settings_work_mem_bytes", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "effective_cache_size",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_effective_cache_size_bytes",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "max_standby_streaming_delay",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_settings_max_standby_streaming_delay_seconds",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Custom Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_database_size_bytes{job=\"primary\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Lag (from primary)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_replication_replay_lag",
       "legendFormat": "{{job}}: {{application_name}}@{{client_addr}}"
      }
     ]
    },
    {
     "title": "Replication Lab (from replica)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "pg_replication_replag{job!=\"primary\"}",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "XLOG Position",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "hex" } },
     "targets": [
      { "expr": "pg_xlog_position", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "XLOG Diff",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "max(pg_xlog_position) - min(pg_xlog_position)"
      },
      { "expr": "1000000000", "legendFormat": "Alert" }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "repeat": "node",
     "targets": [
      {
       "expr": "pg_client_connections_count{job=\"$node\"}",
       "legendFormat": "{{appname}} @ {{client_addr}} on {{datname}}"
      },
      {
       "expr": "pg_settings_max_connections{job=\"$node\"}",
       "legendFormat": "Max Connections"
      }
     ]
    }
   ]
  },
  {
   "title": "Lock Age",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Locks Age",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pg_locksage_start{ query!~\".*substring.*\"} * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "Fragmentation and maintenance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dead tuples",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "pg_stat_user_tables_n_dead_tup{job=\"primary\"}",
       "legendFormat": "{{datname}} {{schemaname}}.{{relname}}"
      },
      {
       "expr": "sum(pg_stat_user_tables_n_dead_tup{job=\"primary\"})",
       "legendFormat": "Total dead tuples"
      }
     ]
    },
    {
     "title": "Global Fragmentation",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_stat_user_tables_n_dead_tup{job=\"primary\"}) / sum(pg_stat_user_tables_n_live_tup{job=\"primary\"})"
      }
     ]
    },
    {
     "title": "Modification Since Analyse",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "pg_stat_user_tables_n_mod_since_analyze",
       "legendFormat": "{{datname}} {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Maintenance events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "targets": [
      {
       "expr": "(rate(pg_stat_user_tables_vacuum_count{job=\"primary\"}[20s]) > 0) / (rate(pg_stat_user_tables_vacuum_count{job=\"primary\"}[20s]) > 0)",
       "legendFormat": "{{datname}} {{schemaname}}.{{relname}} Vacuum"
      },
      {
       "expr": "(rate(pg_stat_user_tables_autovacuum_count{job=\"primary\"}[20s]) > 0) / (rate(pg_stat_user_tables_autovacuum_count{job=\"primary\"}[20s]) > 0)",
       "legendFormat": "{{datname}} {{schemaname}}.{{relname}} AUTO Vacuum"
      },
      {
       "expr": "(rate(pg_stat_user_tables_analyze_count{job=\"primary\"}[20s]) > 0) / (rate(pg_stat_user_tables_analyze_count{job=\"primary\"}[20s]) > 0)",
       "legendFormat": "{{datname}} {{schemaname}}.{{relname}} Analyse"
      },
      {
       "expr": "(rate(pg_stat_user_tables_autoanalyze_count{job=\"primary\"}[20s]) > 0) / (rate(pg_stat_user_tables_autoanalyze_count{job=\"primary\"}[20s]) > 0)",
       "legendFormat": "{{datname}} {{schemaname}}.{{relname}} AUTO Analyse"
      }
     ]
    },
    {
     "title": "Table fragmentation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "pg_stat_user_tables_n_dead_tup / (pg_stat_user_tables_n_live_tup + pg_stat_user_tables_n_dead_tup)",
       "legendFormat": "{{datname}} {{schemaname}} {{relname}}"
      }
     ]
    },
    {
     "title": "Auto Vacuum trigger",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "pg_stat_user_tables_n_dead_tup{job=\"primary\"} /\n(\n    (pg_stat_user_tables_n_live_tup{job=\"primary\"} *\n     ignoring (datname,relname,schemaname) group_left (server) pg_settings_autovacuum_vacuum_scale_factor{job=\"primary\"}\n    ) + ignoring (datname,relname,schemaname) group_left (server) pg_settings_autovacuum_vacuum_threshold{job=\"primary\"}\n)",
       "legendFormat": "{{datname}} {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Seq Scan ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "pg_stat_user_tables_seq_scan / pg_stat_user_tables_idx_scan",
       "legendFormat": "{{datname}} {{schemaname}}.{{relname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Table size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pg_table_size_total_bytes{job=\"primary\", schemaname!~\"pg_catalog|information_schema\"}",
       "legendFormat": "{{datname}} {{schemaname}}.{{relname}}"
      }
     ]
    },
    {
     "title": "Table Size",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "pg_table_size_table_bytes{job=\"primary\", schemaname!~\"pg_catalog|information_schema\"}"
      },
      {
       "expr": "pg_table_size_toast_bytes{job=\"primary\", schemaname!~\"pg_catalog|information_schema\"}"
      },
      {
       "expr": "pg_table_size_index_bytes{job=\"primary\", schemaname!~\"pg_catalog|information_schema\"}"
      },
      {
       "expr": "pg_table_size_total_bytes{job=\"primary\", schemaname!~\"pg_catalog|information_schema\"}"
      },
      {
       "expr": "pg_stat_user_tables_n_dead_tup{job=\"primary\", schemaname!~\"pg_catalog|information_schema\"}"
      },
      {
       "expr": "pg_stat_user_tables_n_live_tup{job=\"primary\", schemaname!~\"pg_catalog|information_schema\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statements",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time consuming Statements",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(3, rate(pg_stat_statements_total_time_seconds[1m]))",
       "legendFormat": "{{shrunk_query_text}}"
      }
     ]
    },
    {
     "title": "Rows involved",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "topk(5, rate(pg_stat_statements_rows[1m]))",
       "legendFormat": "{{shrunk_query_text}}"
      }
     ]
    },
    {
     "title": "Calls rate",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(10, rate(pg_stat_statements_calls[1m]))"
      }
     ]
    }
   ]
  }
 ]
}